import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { TableModule } from 'primeng/table';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [TableModule, CommonModule],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss',
})
export class DashboardComponent {
  products: any[] = [
    {
      orderId: '#45784',
      customer: 'Shuaib',
      date: '16-08-2024',
      paid: 'No',
      status: 'Pending',
      items: 2,
      paymentMode: 'Cash on delivery',
      total: 'AED 1050.00',
      action: 'View Details',
    },
    {
      orderId: '#45784',
      customer: 'Ajmal',
      date: '18-08-2024',
      paid: 'Yes',
      status: 'Delivered',
      items: 3,
      paymentMode: 'Card on delivery',
      total: 'AED 7500.00',
      action: 'View Details',
    },
    {
      orderId: '#45784',
      customer: 'Ismail',
      date: '26-08-2024',
      paid: 'Yes',
      status: 'Cancelled',
      items: 1,
      paymentMode: 'Online Payment',
      total: 'AED 4500.00',
      action: 'View Details',
    },
    {
      orderId: '#45784',
      customer: 'Musthafa',
      date: '16-09-2024',
      paid: 'Yes',
      status: 'Delivered',
      items: 1,
      paymentMode: 'Online Payment',
      total: 'AED 5500.00',
      action: 'View Details',
    },
    {
      orderId: '#45784',
      customer: 'Jabir',
      date: '01-09-2024',
      paid: 'Yes',
      status: 'Returned',
      items: 3,
      paymentMode: 'Card on delivery',
      total: 'AED 1000.00',
      action: 'View Details',
    },
    {
      orderId: '#45784',
      customer: 'Shuaib',
      date: '16-08-2024',
      paid: 'No',
      status: 'Pending',
      items: 2,
      paymentMode: 'Cash on delivery',
      total: 'AED 1050.00',
      action: 'View Details',
    },
    {
      orderId: '#45784',
      customer: 'Ajmal',
      date: '18-08-2024',
      paid: 'Yes',
      status: 'Delivered',
      items: 3,
      paymentMode: 'Card on delivery',
      total: 'AED 7500.00',
      action: 'View Details',
    },
    {
      orderId: '#45784',
      customer: 'Ismail',
      date: '26-08-2024',
      paid: 'Yes',
      status: 'Cancelled',
      items: 1,
      paymentMode: 'Online Payment',
      total: 'AED 4500.00',
      action: 'View Details',
    },
    {
      orderId: '#45784',
      customer: 'Musthafa',
      date: '16-09-2024',
      paid: 'Yes',
      status: 'Delivered',
      items: 1,
      paymentMode: 'Online Payment',
      total: 'AED 5500.00',
      action: 'View Details',
    },
    {
      orderId: '#45784',
      customer: 'Jabir',
      date: '01-09-2024',
      paid: 'Yes',
      status: 'Returned',
      items: 3,
      paymentMode: 'Card on delivery',
      total: 'AED 1000.00',
      action: 'View Details',
    },
  ];

  constructor() {}

  ngOnInit() {}
}
